export const EDIT_LOAD_STATE = 'EDIT_LOAD_STATE';
export const EDIT_CITY_INPUT = 'EDIT_CITY_INPUT';
export const EDIT_WEATHER_IN_CITY = 'EDIT_WEATHER_IN_CITY';
export const EDIT_ERROR_STATE = 'EDIT_ERROR_STATE';
export const SEARCH_WEATHER_IN_CITY = 'SEARCH_WEATHER_IN_CITY';